# Generated by Django 3.1 on 2020-08-30 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no_name', max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('location', models.CharField(default='no_name', max_length=200)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
